# Generated by Django 3.0.4 on 2020-05-17 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='executor_user',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='normal_user',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='user',
            name='vigilant_user',
            field=models.BooleanField(default=False),
        ),
    ]
